//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBatallaNaval.ServicioAServidor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJuegoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJuego {
            get {
                return this.IdJuegoField;
            }
            set {
                if ((this.IdJuegoField.Equals(value) != true)) {
                    this.IdJuegoField = value;
                    this.RaisePropertyChanged("IdJuego");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeEnviado {
            get {
                return this.MensajeEnviadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeEnviadoField, value) != true)) {
                    this.MensajeEnviadoField = value;
                    this.RaisePropertyChanged("MensajeEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAServidor.IAdminiUsuarios")]
    public interface IAdminiUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IAdminiUsuarios/IniciarSesionResponse")]
        bool IniciarSesion(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IAdminiUsuarios/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RegistarUsuario", ReplyAction="http://tempuri.org/IAdminiUsuarios/RegistarUsuarioResponse")]
        bool RegistarUsuario(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RegistarUsuario", ReplyAction="http://tempuri.org/IAdminiUsuarios/RegistarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistarUsuarioAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/CambiarContraseña", ReplyAction="http://tempuri.org/IAdminiUsuarios/CambiarContraseñaResponse")]
        bool CambiarContraseña(string apodo, string contraseñaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/CambiarContraseña", ReplyAction="http://tempuri.org/IAdminiUsuarios/CambiarContraseñaResponse")]
        System.Threading.Tasks.Task<bool> CambiarContraseñaAsync(string apodo, string contraseñaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RecuperarJugadorPorCorreo", ReplyAction="http://tempuri.org/IAdminiUsuarios/RecuperarJugadorPorCorreoResponse")]
        ProyectoBatallaNaval.ServicioAServidor.Jugador RecuperarJugadorPorCorreo(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RecuperarJugadorPorCorreo", ReplyAction="http://tempuri.org/IAdminiUsuarios/RecuperarJugadorPorCorreoResponse")]
        System.Threading.Tasks.Task<ProyectoBatallaNaval.ServicioAServidor.Jugador> RecuperarJugadorPorCorreoAsync(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RecuperarListaDeAmigos", ReplyAction="http://tempuri.org/IAdminiUsuarios/RecuperarListaDeAmigosResponse")]
        string[] RecuperarListaDeAmigos(string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/RecuperarListaDeAmigos", ReplyAction="http://tempuri.org/IAdminiUsuarios/RecuperarListaDeAmigosResponse")]
        System.Threading.Tasks.Task<string[]> RecuperarListaDeAmigosAsync(string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/AñadirAmigo", ReplyAction="http://tempuri.org/IAdminiUsuarios/AñadirAmigoResponse")]
        bool AñadirAmigo(string apodoJugador, string apodoAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/AñadirAmigo", ReplyAction="http://tempuri.org/IAdminiUsuarios/AñadirAmigoResponse")]
        System.Threading.Tasks.Task<bool> AñadirAmigoAsync(string apodoJugador, string apodoAmigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiUsuariosChannel : ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminiUsuariosClient : System.ServiceModel.ClientBase<ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios>, ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios {
        
        public AdminiUsuariosClient() {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesion(string usuario, string contraseña) {
            return base.Channel.IniciarSesion(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contraseña) {
            return base.Channel.IniciarSesionAsync(usuario, contraseña);
        }
        
        public bool RegistarUsuario(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.RegistarUsuario(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> RegistarUsuarioAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.RegistarUsuarioAsync(jugador);
        }
        
        public bool CambiarContraseña(string apodo, string contraseñaNueva) {
            return base.Channel.CambiarContraseña(apodo, contraseñaNueva);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarContraseñaAsync(string apodo, string contraseñaNueva) {
            return base.Channel.CambiarContraseñaAsync(apodo, contraseñaNueva);
        }
        
        public ProyectoBatallaNaval.ServicioAServidor.Jugador RecuperarJugadorPorCorreo(string correoElectronico) {
            return base.Channel.RecuperarJugadorPorCorreo(correoElectronico);
        }
        
        public System.Threading.Tasks.Task<ProyectoBatallaNaval.ServicioAServidor.Jugador> RecuperarJugadorPorCorreoAsync(string correoElectronico) {
            return base.Channel.RecuperarJugadorPorCorreoAsync(correoElectronico);
        }
        
        public string[] RecuperarListaDeAmigos(string nombreJugador) {
            return base.Channel.RecuperarListaDeAmigos(nombreJugador);
        }
        
        public System.Threading.Tasks.Task<string[]> RecuperarListaDeAmigosAsync(string nombreJugador) {
            return base.Channel.RecuperarListaDeAmigosAsync(nombreJugador);
        }
        
        public bool AñadirAmigo(string apodoJugador, string apodoAmigo) {
            return base.Channel.AñadirAmigo(apodoJugador, apodoAmigo);
        }
        
        public System.Threading.Tasks.Task<bool> AñadirAmigoAsync(string apodoJugador, string apodoAmigo) {
            return base.Channel.AñadirAmigoAsync(apodoJugador, apodoAmigo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAServidor.IAdminiSocial", CallbackContract=typeof(ProyectoBatallaNaval.ServicioAServidor.IAdminiSocialCallback))]
    public interface IAdminiSocial {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Conectado")]
        void Conectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Conectado")]
        System.Threading.Tasks.Task ConectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Desconectado")]
        void Desconectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Desconectado")]
        System.Threading.Tasks.Task DesconectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/EnviarMensaje")]
        void EnviarMensaje(ProyectoBatallaNaval.ServicioAServidor.Chat mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(ProyectoBatallaNaval.ServicioAServidor.Chat mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CrearSala")]
        void CrearSala(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CrearSala")]
        System.Threading.Tasks.Task CrearSalaAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/UnirseASala")]
        void UnirseASala(string sala, ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/UnirseASala")]
        System.Threading.Tasks.Task UnirseASalaAsync(string sala, ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TodoListo")]
        void TodoListo(string sala, string jugador, int numeroDeListos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TodoListo")]
        System.Threading.Tasks.Task TodoListoAsync(string sala, string jugador, int numeroDeListos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CancelarTodoListo")]
        void CancelarTodoListo(string sala, string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CancelarTodoListo")]
        System.Threading.Tasks.Task CancelarTodoListoAsync(string sala, string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/EliminarSala")]
        void EliminarSala(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/EliminarSala")]
        System.Threading.Tasks.Task EliminarSalaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Tiro")]
        void Tiro(string coordenadas, string contricante, string sala, string NombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Tiro")]
        System.Threading.Tasks.Task TiroAsync(string coordenadas, string contricante, string sala, string NombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/IniciarPartida")]
        void IniciarPartida(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/IniciarPartida")]
        System.Threading.Tasks.Task IniciarPartidaAsync(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TerminarPartida")]
        void TerminarPartida(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TerminarPartida")]
        System.Threading.Tasks.Task TerminarPartidaAsync(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/PrimerTiro")]
        void PrimerTiro(string jugador1, string jugador2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/PrimerTiro")]
        System.Threading.Tasks.Task PrimerTiroAsync(string jugador1, string jugador2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/ActualizarCallbackEnPartida")]
        void ActualizarCallbackEnPartida(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/ActualizarCallbackEnPartida")]
        System.Threading.Tasks.Task ActualizarCallbackEnPartidaAsync(string jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/PartidaGanada")]
        void PartidaGanada(string janador, string jugadorParaNotificar);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/PartidaGanada")]
        System.Threading.Tasks.Task PartidaGanadaAsync(string janador, string jugadorParaNotificar);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TiroCertero")]
        void TiroCertero(string coordenadas, string contricante);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/TiroCertero")]
        System.Threading.Tasks.Task TiroCerteroAsync(string coordenadas, string contricante);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CerrarJuego")]
        void CerrarJuego(string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/CerrarJuego")]
        System.Threading.Tasks.Task CerrarJuegoAsync(string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/ExpulsarDeSala")]
        void ExpulsarDeSala(string sala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/ExpulsarDeSala")]
        System.Threading.Tasks.Task ExpulsarDeSalaAsync(string sala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiSocialCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/ActualizarJugadores")]
        void ActualizarJugadores(ProyectoBatallaNaval.ServicioAServidor.Jugador[] jugadores);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/UnionDeJugador")]
        void UnionDeJugador(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/JugadorSeFue")]
        void JugadorSeFue(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/EscribiendoEnCallback")]
        void EscribiendoEnCallback(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirMensaje", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirMensajeResponse")]
        void RecibirMensaje(ProyectoBatallaNaval.ServicioAServidor.Chat respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirCodigoSala", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirCodigoSalaResponse")]
        void RecibirCodigoSala(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/JugadorSeUnio", ReplyAction="http://tempuri.org/IAdminiSocial/JugadorSeUnioResponse")]
        void JugadorSeUnio(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador, string sala, bool seUnio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirTodoListo", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirTodoListoResponse")]
        void RecibirTodoListo(string contricante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirTodoListoParaIniciar", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirTodoListoParaIniciarResponse")]
        void RecibirTodoListoParaIniciar(string contricante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirCancelarListo", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirCancelarListoResponse")]
        void RecibirCancelarListo(string contricante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/InsertarDisparo", ReplyAction="http://tempuri.org/IAdminiSocial/InsertarDisparoResponse")]
        void InsertarDisparo(string coordenadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/IniciarPartidaCallback", ReplyAction="http://tempuri.org/IAdminiSocial/IniciarPartidaCallbackResponse")]
        void IniciarPartidaCallback(bool inicar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/PrimerTiroCallback", ReplyAction="http://tempuri.org/IAdminiSocial/PrimerTiroCallbackResponse")]
        void PrimerTiroCallback(bool iniciar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/PartidaGanadaCallback", ReplyAction="http://tempuri.org/IAdminiSocial/PartidaGanadaCallbackResponse")]
        void PartidaGanadaCallback(string jugadorGanado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/ActualizarCallbackEnPartidaCallback", ReplyAction="http://tempuri.org/IAdminiSocial/ActualizarCallbackEnPartidaCallbackResponse")]
        void ActualizarCallbackEnPartidaCallback(bool actualizado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/TiroCerteroCallback", ReplyAction="http://tempuri.org/IAdminiSocial/TiroCerteroCallbackResponse")]
        void TiroCerteroCallback(string coordenadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/RecibirExpulsacion", ReplyAction="http://tempuri.org/IAdminiSocial/RecibirExpulsacionResponse")]
        void RecibirExpulsacion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiSocialChannel : ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminiSocialClient : System.ServiceModel.DuplexClientBase<ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial>, ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial {
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Conectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.Conectado(jugador);
        }
        
        public System.Threading.Tasks.Task ConectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.ConectadoAsync(jugador);
        }
        
        public void Desconectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.Desconectado(jugador);
        }
        
        public System.Threading.Tasks.Task DesconectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.DesconectadoAsync(jugador);
        }
        
        public void EnviarMensaje(ProyectoBatallaNaval.ServicioAServidor.Chat mensaje) {
            base.Channel.EnviarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(ProyectoBatallaNaval.ServicioAServidor.Chat mensaje) {
            return base.Channel.EnviarMensajeAsync(mensaje);
        }
        
        public void CrearSala(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.CrearSala(jugador);
        }
        
        public System.Threading.Tasks.Task CrearSalaAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.CrearSalaAsync(jugador);
        }
        
        public void UnirseASala(string sala, ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.UnirseASala(sala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseASalaAsync(string sala, ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.UnirseASalaAsync(sala, jugador);
        }
        
        public void TodoListo(string sala, string jugador, int numeroDeListos) {
            base.Channel.TodoListo(sala, jugador, numeroDeListos);
        }
        
        public System.Threading.Tasks.Task TodoListoAsync(string sala, string jugador, int numeroDeListos) {
            return base.Channel.TodoListoAsync(sala, jugador, numeroDeListos);
        }
        
        public void CancelarTodoListo(string sala, string jugador) {
            base.Channel.CancelarTodoListo(sala, jugador);
        }
        
        public System.Threading.Tasks.Task CancelarTodoListoAsync(string sala, string jugador) {
            return base.Channel.CancelarTodoListoAsync(sala, jugador);
        }
        
        public void EliminarSala(string codigoSala) {
            base.Channel.EliminarSala(codigoSala);
        }
        
        public System.Threading.Tasks.Task EliminarSalaAsync(string codigoSala) {
            return base.Channel.EliminarSalaAsync(codigoSala);
        }
        
        public void Tiro(string coordenadas, string contricante, string sala, string NombreJugador) {
            base.Channel.Tiro(coordenadas, contricante, sala, NombreJugador);
        }
        
        public System.Threading.Tasks.Task TiroAsync(string coordenadas, string contricante, string sala, string NombreJugador) {
            return base.Channel.TiroAsync(coordenadas, contricante, sala, NombreJugador);
        }
        
        public void IniciarPartida(string jugador) {
            base.Channel.IniciarPartida(jugador);
        }
        
        public System.Threading.Tasks.Task IniciarPartidaAsync(string jugador) {
            return base.Channel.IniciarPartidaAsync(jugador);
        }
        
        public void TerminarPartida(string jugador) {
            base.Channel.TerminarPartida(jugador);
        }
        
        public System.Threading.Tasks.Task TerminarPartidaAsync(string jugador) {
            return base.Channel.TerminarPartidaAsync(jugador);
        }
        
        public void PrimerTiro(string jugador1, string jugador2) {
            base.Channel.PrimerTiro(jugador1, jugador2);
        }
        
        public System.Threading.Tasks.Task PrimerTiroAsync(string jugador1, string jugador2) {
            return base.Channel.PrimerTiroAsync(jugador1, jugador2);
        }
        
        public void ActualizarCallbackEnPartida(string jugador) {
            base.Channel.ActualizarCallbackEnPartida(jugador);
        }
        
        public System.Threading.Tasks.Task ActualizarCallbackEnPartidaAsync(string jugador) {
            return base.Channel.ActualizarCallbackEnPartidaAsync(jugador);
        }
        
        public void PartidaGanada(string janador, string jugadorParaNotificar) {
            base.Channel.PartidaGanada(janador, jugadorParaNotificar);
        }
        
        public System.Threading.Tasks.Task PartidaGanadaAsync(string janador, string jugadorParaNotificar) {
            return base.Channel.PartidaGanadaAsync(janador, jugadorParaNotificar);
        }
        
        public void TiroCertero(string coordenadas, string contricante) {
            base.Channel.TiroCertero(coordenadas, contricante);
        }
        
        public System.Threading.Tasks.Task TiroCerteroAsync(string coordenadas, string contricante) {
            return base.Channel.TiroCerteroAsync(coordenadas, contricante);
        }
        
        public void CerrarJuego(string nombreJugador) {
            base.Channel.CerrarJuego(nombreJugador);
        }
        
        public System.Threading.Tasks.Task CerrarJuegoAsync(string nombreJugador) {
            return base.Channel.CerrarJuegoAsync(nombreJugador);
        }
        
        public void ExpulsarDeSala(string sala) {
            base.Channel.ExpulsarDeSala(sala);
        }
        
        public System.Threading.Tasks.Task ExpulsarDeSalaAsync(string sala) {
            return base.Channel.ExpulsarDeSalaAsync(sala);
        }
    }
}
