//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBatallaNaval.ServicioAServidor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJuegoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJuego {
            get {
                return this.IdJuegoField;
            }
            set {
                if ((this.IdJuegoField.Equals(value) != true)) {
                    this.IdJuegoField = value;
                    this.RaisePropertyChanged("IdJuego");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAServidor.IAdminiUsuarios")]
    public interface IAdminiUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/iniciarSesion", ReplyAction="http://tempuri.org/IAdminiUsuarios/iniciarSesionResponse")]
        bool iniciarSesion(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/iniciarSesion", ReplyAction="http://tempuri.org/IAdminiUsuarios/iniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> iniciarSesionAsync(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/registarUsuario", ReplyAction="http://tempuri.org/IAdminiUsuarios/registarUsuarioResponse")]
        bool registarUsuario(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/registarUsuario", ReplyAction="http://tempuri.org/IAdminiUsuarios/registarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> registarUsuarioAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/cambiarContraseña", ReplyAction="http://tempuri.org/IAdminiUsuarios/cambiarContraseñaResponse")]
        bool cambiarContraseña(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiUsuarios/cambiarContraseña", ReplyAction="http://tempuri.org/IAdminiUsuarios/cambiarContraseñaResponse")]
        System.Threading.Tasks.Task<bool> cambiarContraseñaAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiUsuariosChannel : ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminiUsuariosClient : System.ServiceModel.ClientBase<ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios>, ProyectoBatallaNaval.ServicioAServidor.IAdminiUsuarios {
        
        public AdminiUsuariosClient() {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool iniciarSesion(string usuario, string contraseña) {
            return base.Channel.iniciarSesion(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> iniciarSesionAsync(string usuario, string contraseña) {
            return base.Channel.iniciarSesionAsync(usuario, contraseña);
        }
        
        public bool registarUsuario(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.registarUsuario(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> registarUsuarioAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.registarUsuarioAsync(jugador);
        }
        
        public bool cambiarContraseña(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.cambiarContraseña(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> cambiarContraseñaAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.cambiarContraseñaAsync(jugador);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAServidor.IAdminiSocial", CallbackContract=typeof(ProyectoBatallaNaval.ServicioAServidor.IAdminiSocialCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAdminiSocial {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Conectado")]
        void Conectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/Conectado")]
        System.Threading.Tasks.Task ConectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/estaEscribiendo")]
        void estaEscribiendo(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/estaEscribiendo")]
        System.Threading.Tasks.Task estaEscribiendoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IAdminiSocial/desconectado")]
        void desconectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IAdminiSocial/desconectado")]
        System.Threading.Tasks.Task desconectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/enviarMensaje")]
        void enviarMensaje(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/enviarMensaje")]
        System.Threading.Tasks.Task enviarMensajeAsync(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiSocialCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/actualizarJugadores")]
        void actualizarJugadores(ProyectoBatallaNaval.ServicioAServidor.Jugador[] jugadores);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/unionDeJugador")]
        void unionDeJugador(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/jugadorSeFue")]
        void jugadorSeFue(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminiSocial/escribiendoEnCallback")]
        void escribiendoEnCallback(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiSocial/recibirMensaje", ReplyAction="http://tempuri.org/IAdminiSocial/recibirMensajeResponse")]
        void recibirMensaje(string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiSocialChannel : ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminiSocialClient : System.ServiceModel.DuplexClientBase<ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial>, ProyectoBatallaNaval.ServicioAServidor.IAdminiSocial {
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiSocialClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Conectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.Conectado(jugador);
        }
        
        public System.Threading.Tasks.Task ConectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.ConectadoAsync(jugador);
        }
        
        public void estaEscribiendo(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.estaEscribiendo(jugador);
        }
        
        public System.Threading.Tasks.Task estaEscribiendoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.estaEscribiendoAsync(jugador);
        }
        
        public void desconectado(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            base.Channel.desconectado(jugador);
        }
        
        public System.Threading.Tasks.Task desconectadoAsync(ProyectoBatallaNaval.ServicioAServidor.Jugador jugador) {
            return base.Channel.desconectadoAsync(jugador);
        }
        
        public void enviarMensaje(string mensaje) {
            base.Channel.enviarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task enviarMensajeAsync(string mensaje) {
            return base.Channel.enviarMensajeAsync(mensaje);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAServidor.IAdminiPartida", CallbackContract=typeof(ProyectoBatallaNaval.ServicioAServidor.IAdminiPartidaCallback))]
    public interface IAdminiPartida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiPartida/tiro", ReplyAction="http://tempuri.org/IAdminiPartida/tiroResponse")]
        bool tiro(int[] coordenadas, string contricante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiPartida/tiro", ReplyAction="http://tempuri.org/IAdminiPartida/tiroResponse")]
        System.Threading.Tasks.Task<bool> tiroAsync(int[] coordenadas, string contricante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiPartidaCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminiPartida/insertarDisparo", ReplyAction="http://tempuri.org/IAdminiPartida/insertarDisparoResponse")]
        bool insertarDisparo(int[] coordenadas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminiPartidaChannel : ProyectoBatallaNaval.ServicioAServidor.IAdminiPartida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminiPartidaClient : System.ServiceModel.DuplexClientBase<ProyectoBatallaNaval.ServicioAServidor.IAdminiPartida>, ProyectoBatallaNaval.ServicioAServidor.IAdminiPartida {
        
        public AdminiPartidaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdminiPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdminiPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminiPartidaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool tiro(int[] coordenadas, string contricante) {
            return base.Channel.tiro(coordenadas, contricante);
        }
        
        public System.Threading.Tasks.Task<bool> tiroAsync(int[] coordenadas, string contricante) {
            return base.Channel.tiroAsync(coordenadas, contricante);
        }
    }
}
