//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBatallaNaval.Properties.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoBatallaNaval.Properties.Idiomas.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        public static string cambiarIdioma {
            get {
                return ResourceManager.GetString("cambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a casilla_.
        /// </summary>
        public static string casilla {
            get {
                return ResourceManager.GetString("casilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ingresado es invalido, deben ser de 5 caracteres.
        /// </summary>
        public static string codigoInvalido {
            get {
                return ResourceManager.GetString("codigoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma la contraseña.
        /// </summary>
        public static string confirmaContraseña {
            get {
                return ResourceManager.GetString("confirmaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string confirmarContraseña {
            get {
                return ResourceManager.GetString("confirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas deben coincidir .
        /// </summary>
        public static string contraseñasDiferentes {
            get {
                return ResourceManager.GetString("contraseñasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        public static string correoElectronico {
            get {
                return ResourceManager.GetString("correoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un Correo electronico valido..
        /// </summary>
        public static string correoInvalido {
            get {
                return ResourceManager.GetString("correoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string crearPartida {
            get {
                return ResourceManager.GetString("crearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups, tenemos problema para obtener informacion, intentalo más tarde.
        /// </summary>
        public static string ErrorConexionBaseDeDatos {
            get {
                return ResourceManager.GetString("ErrorConexionBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no responde, vuelve a intentarlo más tarde.
        /// </summary>
        public static string ErrorConexionServidor {
            get {
                return ResourceManager.GetString("ErrorConexionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intenta con otros datos.
        /// </summary>
        public static string ErrorDatosDuplicados {
            get {
                return ResourceManager.GetString("ErrorDatosDuplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timpo agotado al procesar la solicitud, vuelve a intentarlo en unos minutos.
        /// </summary>
        public static string ErrorTiempoAgotado {
            get {
                return ResourceManager.GetString("ErrorTiempoAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe una contraseña.
        /// </summary>
        public static string escribaContraseña {
            get {
                return ResourceManager.GetString("escribaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un correo electronico.
        /// </summary>
        public static string escribeCorreoElectronico {
            get {
                return ResourceManager.GetString("escribeCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string español {
            get {
                return ResourceManager.GetString("español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string expulsar {
            get {
                return ResourceManager.GetString("expulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta fallando el lobby.
        /// </summary>
        public static string fallaEnLobby {
            get {
                return ResourceManager.GetString("fallaEnLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe haber dos personas en la sala para poder jugar.
        /// </summary>
        public static string faltanJugadores {
            get {
                return ResourceManager.GetString("faltanJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has ganado, felicidades.
        /// </summary>
        public static string hasGanando {
            get {
                return ResourceManager.GetString("hasGanando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has perdido :(.
        /// </summary>
        public static string hasPerdido {
            get {
                return ResourceManager.GetString("hasPerdido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string ingles {
            get {
                return ResourceManager.GetString("ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden dejar campos vacios.
        /// </summary>
        public static string noCamposVacios {
            get {
                return ResourceManager.GetString("noCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string nombreUsuario {
            get {
                return ResourceManager.GetString("nombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida.
        /// </summary>
        public static string partida {
            get {
                return ResourceManager.GetString("partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propia.
        /// </summary>
        public static string propia {
            get {
                return ResourceManager.GetString("propia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala a la que intenta unirse se encuentra llena.
        /// </summary>
        public static string salaLlena {
            get {
                return ResourceManager.GetString("salaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea abandonar la partida y salir del juego?.
        /// </summary>
        public static string salirDelJuego {
            get {
                return ResourceManager.GetString("salirDelJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirar.
        /// </summary>
        public static string tirar {
            get {
                return ResourceManager.GetString("tirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todo listo.
        /// </summary>
        public static string todoListo {
            get {
                return ResourceManager.GetString("todoListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Tu).
        /// </summary>
        public static string tu {
            get {
                return ResourceManager.GetString("tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala..
        /// </summary>
        public static string unirseSala {
            get {
                return ResourceManager.GetString("unirseSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no esta registrado.
        /// </summary>
        public static string usuarioNoRegistrado {
            get {
                return ResourceManager.GetString("usuarioNoRegistrado", resourceCulture);
            }
        }
    }
}
